# 7. Numpy
 - Numpy就是数组：只能存储一种类型的数据
 - List: 可以存储多种类型的数据 
 - np.array(a_list)：把列表转换为数组
 - np.zeros((5,4), dtype=int)：初始化5行4列数组（元素数据类型为int，值为0）
 - np.ones((3,4), dtype=float):初始化3行4列数组（元素数据类型为float，值为1）
 - np.full((3,5), 3.14)：所有元素的值都为3.14
 - np.random.random((3,4))：所有元素为(0,1)间的随机数
 - np.random.randint(5,10,(3,4))：所有元素为[5,10]间的随机数
 - numpy的数据类型：
  - bool_, 
  - int_, intc, intp, int8, int16, int32, int64, 
  - uint8, uint 16, uint32, uint64, 
   - float_, float16, float32, float64, complex_, complex64, complex128
 - a[i,j]与a[i][j]:是等价的
 - b[:2, :2] (取前2行及2列)  与 b[:2][:2] (取前面2行)：是不等价的 
 

## 7.1 数组初始化

In [ ]:
import array
a = array.array('i', range(10))
a[1]

In [10]:
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np

 - 从原有列表转换为数组

In [22]:
a_list = list(range(10))
b = np.array(a_list)   # 从原有列表转换为数组
type(b)]
print('a_list=',a_list)
print('b=',b)

a_list= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b= [0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
a = np.zeros(10, dtype=int)
print(a)
print(type(a))
a.dtype

[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


dtype('int32')

In [27]:
a = np.zeros((5,4), dtype=int)
print(a)
print(type(a))
a.dtype

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>


dtype('int32')

In [31]:
a = np.ones((3,4), dtype=float)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
a = np.full((3,5), 3.14) # 所有元素的值都为3.14
print('a=',a)

## 使用另一个元素的行和列
b = np.zeros_like(a)
print('b=',b)
c = np.ones_like(a)
print('c=',c)
d = np.full_like(a, 99.2, dtype=float)
print('d=',d)

a= [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
b= [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
c= [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
d= [[99.2 99.2 99.2 99.2 99.2]
 [99.2 99.2 99.2 99.2 99.2]
 [99.2 99.2 99.2 99.2 99.2]]


 - random

In [2]:
import random
print(random.randint(5,10)) # 生成一个[5,10]之间的一个整数 
print(random.random()) # 生成一个0-1之间的一个浮点数

9
0.6135262874360777


In [101]:
np.random.random()  # 生成一个0-1之间的一个浮点数

0.46137828215717525

In [102]:
## 常用的函数
np.random.random((3,4))

array([[0.84777354, 0.17187269, 0.35159653, 0.77756519],
       [0.44120604, 0.77547163, 0.94242698, 0.99595079],
       [0.26863972, 0.98666442, 0.57185265, 0.296414  ]])

In [20]:
## 常用的函数
np.random.randint(5,10,(3,4))

array([[9, 8, 6, 9],
       [8, 7, 9, 7],
       [9, 8, 5, 5]])

 - 范围取值

In [108]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [109]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [111]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [115]:
# 经常使用
np.linspace(0,3,10) # 共10个元素，元素值为[0,3]间的等差数列 (step = (3-0)/(10-1))

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [117]:
np.eye(3) # 生成单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 7.2 访问数组中元素

In [26]:
# 访问列表元素
a = [[1,2,3], [4,5,6]]
a[0][0]

1

In [27]:
import numpy as np

In [28]:
a = np.full((3,3),3.14, dtype=float)
a

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [29]:
a[0][1], a[0,1]  # 是等价的

(3.14, 3.14)

## 7.2 数组切片

In [16]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b[0,1], b[0,1]

(2, 2)

In [30]:
b[:2][:2] # 取前两行，再取前两行

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b[:2, :2]  # 与b[:2][:2]是不等价的

array([[1, 2],
       [4, 5]])

## 7.3 数组属性

 - 维度和shape

import numpy as np
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)

print('ndim={}'.format(b.ndim))  # 维数

print('shape={}'.format(b.shape)) # 每维元素个数

print('size={}'.format(b.size)) # 总的元素个数

print('b.type={}'.format(b.dtype))  # 数据元素类型

print('b.itemsize={}'.format(b.itemsize)) # 每个元素所占字节数

print('b.bytes={}'.format(b.nbytes))  # 数组所占总字节数
      

## 7.4 数组运算
 - 对数组中每个元素做相同运算
 -  $+$ : np.add
 -  $-$ : np.subtract
 -  $-$ : np.negative
 - $*$ : np.multiply
 - / : np.divide
 - // : np.floor_divide
 - ** : np.power
 - % : np.mod

In [56]:
import numpy as np

a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
c = np.ones((3,3))
d = np.full((3,3),2)
print('b+c=', b+c)
print('b-c=', b-c)

print('b+100=', b+100)
print('b*100=', b*100)
print('b*d=', b*d)

print('b**2=', b**2)

b+c= [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
b-c= [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
b+100= [[101 102 103]
 [104 105 106]
 [107 108 109]]
b*100= [[100 200 300]
 [400 500 600]
 [700 800 900]]
b*d= [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
b**2= [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [61]:
a = np.linspace(0, np.pi, 5)
b = np.sin(a)
print(a)
print(b)

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


## 7.5 统计类型 

In [76]:
# 求和
a = list(range(5))
print(a)
print(sum(a))

b = np.array(a)
print(b)
print(sum(b))

a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
print(b)
print(sum(b))  # 按列求和

print('np.sum(b)=',np.sum(b)) # 求所有元素的和
print('np.sum(b,axis=0)', np.sum(b,axis=0)) # 按列求和
print('np.sum(b,axis=1)', np.sum(b,axis=1)) # 按行求和

print('np.max(b)=',np.max(b)) # 求所有元素的最大值
print('np.max(b,axis=0)', np.max(b,axis=0)) # 按列求最大值
print('np.max(b,axis=1)', np.max(b,axis=1)) # 按行求最大值

print('np.min(b)=',np.min(b)) # 求所有元素的最小值
print('np.min(b,axis=0)', np.min(b,axis=0)) # 按列求最小值
print('np.min(b,axis=1)', np.min(b,axis=1)) # 按行求最小值

[0, 1, 2, 3, 4]
10
[0 1 2 3 4]
10
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
np.sum(b)= 45
np.sum(b,axis=0) [12 15 18]
np.sum(b,axis=1) [ 6 15 24]
np.max(b)= 9
np.max(b,axis=0) [7 8 9]
np.max(b,axis=1) [3 6 9]
np.min(b)= 1
np.min(b,axis=0) [1 2 3]
np.min(b,axis=1) [1 4 7]


## 7.6 notebook使用小技巧

%timeit代码：此方法用来判断程序的执行效率

In [99]:
a = np.random.rand(100)
a

array([0.83151991, 0.18115798, 0.20184886, 0.138653  , 0.90875124,
       0.34214558, 0.29166896, 0.03355723, 0.98180314, 0.41599962,
       0.14287343, 0.48070526, 0.90479207, 0.31706716, 0.03589617,
       0.12101405, 0.54100569, 0.80613744, 0.45190605, 0.71812867,
       0.68323077, 0.00587597, 0.15573007, 0.65299496, 0.70164793,
       0.57767533, 0.88439965, 0.75268012, 0.53095464, 0.56874502,
       0.53722181, 0.72107354, 0.81838399, 0.28035603, 0.77392764,
       0.61591009, 0.84207189, 0.51149444, 0.23096016, 0.56448798,
       0.75186561, 0.58725355, 0.87013507, 0.79803729, 0.16253317,
       0.14628755, 0.86129134, 0.71784874, 0.52833166, 0.36557145,
       0.83560234, 0.22505832, 0.23392824, 0.76486871, 0.69915042,
       0.01792046, 0.7649934 , 0.31603263, 0.06567721, 0.78149938,
       0.75836266, 0.1245451 , 0.27786463, 0.49471202, 0.27840235,
       0.12704624, 0.78111986, 0.25405578, 0.86954346, 0.34604519,
       0.21727725, 0.72738352, 0.0297987 , 0.07017101, 0.25149

In [100]:
%timeit sum(a)

23 µs ± 981 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [101]:
%timeit np.sum(a) # 执行效率更高

2.43 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 7.7 比较

In [102]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [104]:
a == a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [105]:
a!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [106]:
np.all(a>-1)

True

In [107]:
np.all(a>5)

False

In [108]:
np.any(a>-1)

True

## 7.8 变形

In [117]:
a = np.full((2,10),2)
print(a.shape)
b = a.reshape(4,5)
print(b.shape)
b

(2, 10)
(4, 5)


array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

## 7.9 排序

In [129]:
a = [[1,4,2],[34,3,93],[80,8,22]]
b = np.array(a)
b

array([[ 1,  4,  2],
       [34,  3, 93],
       [80,  8, 22]])

In [131]:
c = np.sort(b)
c

array([[ 1,  2,  4],
       [ 3, 34, 93],
       [ 8, 22, 80]])

In [128]:
b.sort()
b

array([[ 1,  2,  4],
       [ 3, 34, 93],
       [ 8, 22, 80]])

In [133]:
b.sort(axis=0)
b

array([[ 1,  3,  2],
       [34,  4, 22],
       [80,  8, 93]])

## 7.10 拼接

In [139]:
a = np.array([1,2,3])
b = np.array([[9,2,3], [1,3,6]])
print(a)
print(b)
np.concatenate([b,b,b])

[1 2 3]
[[9 2 3]
 [1 3 6]]


array([[9, 2, 3],
       [1, 3, 6],
       [9, 2, 3],
       [1, 3, 6],
       [9, 2, 3],
       [1, 3, 6]])

In [140]:
np.concatenate([b,b,b], axis = 0)

array([[9, 2, 3],
       [1, 3, 6],
       [9, 2, 3],
       [1, 3, 6],
       [9, 2, 3],
       [1, 3, 6]])

In [141]:
np.concatenate([b,b,b], axis = 1)

array([[9, 2, 3, 9, 2, 3, 9, 2, 3],
       [1, 3, 6, 1, 3, 6, 1, 3, 6]])